export const config = {
    baseWidth: 800,
    baseHeight: 500,
    color: "rgb(240, 240, 240)",
    flagSize: 80,
    photoX: 45,
    photoY: 80,
    labelX: 100,
    textX: 295,
    textY: 314,
    qrX: 573,
    qrY: 101,
    flagX: 580,
    flagY: 206,
    font: "'Verdana', sans-serif",
    defaultPhotoSize: 192,
    qrSize: 100,
    qrSpacing: 10,
    promodsX: 20,
    promodsY: 314,
    dbusworldX: 20,
    dbusworldY: 374,
    logoWidth: 67,
    logoHeight: 50,
    vtcLogoSize: 100,
    titleFontSize: 30,
    textFontSize: 24,
    footerFontSize: 22,
    watermarkWidth: 180,
    watermarkHeight: 180,
    lineHeight: 28
};

export const translations = {
    es: {
        pageTitle: "Convoyrama | Generador de Licencia",
        headerTitle: "Generador de Licencia de Conductor",
        navLicense: "Licencia",
        nameLabel: "Nombre:",
        nicknameLabel: "TAG Épico:",
        titleToggleLabel: "Usar título cómico:",
        photoLabel: "Foto (Opcional):",
        countryLabel: "País:",
        companyLinkLabel: "Enlace Perfil Empresa en TMP:",
        truckersmpLinkLabel: "Enlace Perfil en TMP:",
        customTitleLabel: "Cambiar título:",
        watermarkToggleLabel: "Usar marca de agua:",
        qrColorToggleLabel: "Color QR: Oscuro / Claro",
        vtcLogoLabel: "Logo VTC (Opcional):",
        backgroundToggleLabel: "Fondo:",
        colorLabel: "Tono del fondo:",
        saturationLabel: "Saturación:",
        customTitlePlaceholder: "Título personalizado (máx. 36 caracteres, opcional)",
        validLink: "Enlace válido",
        invalidLink: "Enlace inválido: debe ser https://truckersmp.com/user/[...]",
        validCompanyLink: "Enlace de empresa válido",
        invalidCompanyLink: "Enlace inválido: debe ser https://truckersmp.com/vtc/[...]",
        downloadButton: "Descargar Licencia",
        canvasName: "Nombre :",
        canvasLicenseNo: "Núm. Licencia :",
        canvasLevel: "Generación :",
        canvasDate: "Fecha :",
        canvasCountry: "País :",
        canvasTag: "TAG :",
        levelFormat: "{0}{1}",
        titleNormal: "PERMISO DE CONDUCCIÓN INTERNACIONAL",
        titleComedic: "PERMISO PARA CHOCAR EN CONVOY",
        countryPlaceholder: "Seleccione un país",
        tooltipMessage: "Esta licencia es una broma y un guiño a la comunidad, no pretende ser algo profesional.",
        infoTooltip: "Significado de los elementos:\n- Generaciones: TruckersMP comenzó en 2013 y las VTCs en 2019. Las generaciones se calculan aproximando el año de registro del perfil y la VTC.\n- Estrella dorada (✵) junto al nombre: Indica que el usuario es dueño de una VTC. Se puede solicitar abriendo un ticket en el Discord de LAG'S SPEED.\n- Estrellas plateadas (★) a la derecha: Un guiño a la extinta VTC Convoy Nocturno.\n- Símbolo (✓) junto a la fecha: Indica que la fecha proviene de una fuente en línea confiable. Refresca la página para intentar obtener la fecha en línea nuevamente.\n- Símbolo (✗) junto a la fecha: Indica que la fecha es local, no verificada. Refresca la página para intentar obtener la fecha en línea nuevamente.\n- Un verso nocturno susurra un secreto, ¿qué palabra desata el camino oculto?"
    },
    en: {
        pageTitle: "Convoyrama | Driver License Generator",
        headerTitle: "Driver License Generator",
        navLicense: "License",
        nameLabel: "Name:",
        nicknameLabel: "Epic TAG:",
        titleToggleLabel: "Use comedic title:",
        photoLabel: "Photo (Optional):",
        countryLabel: "Country:",
        companyLinkLabel: "TruckersMP Company Profile Link:",
        truckersmpLinkLabel: "TruckersMP Profile Link:",
        customTitleLabel: "Change title:",
        watermarkToggleLabel: "Use watermark:",
        qrColorToggleLabel: "QR Color: Dark / Light",
        vtcLogoLabel: "VTC Logo (Optional):",
        backgroundToggleLabel: "Background:",
        colorLabel: "Background hue:",
        saturationLabel: "Saturation:",
        customTitlePlaceholder: "Custom title (max 36 characters, optional)",
        validLink: "Valid link",
        invalidLink: "Invalid link: must be https://truckersmp.com/user/[...]",
        validCompanyLink: "Valid company link",
        invalidCompanyLink: "Invalid link: must be https://truckersmp.com/vtc/[...]",
        downloadButton: "Download License",
        canvasName: "Name :",
        canvasLicenseNo: "License No. :",
        canvasLevel: "Generation :",
        canvasDate: "Date :",
        canvasCountry: "Country :",
        canvasTag: "TAG :",
        levelFormat: "{0}{1}",
        titleNormal: "INTERNATIONAL DRIVING LICENSE",
        titleComedic: "CONVOY CRASHING PERMIT",
        countryPlaceholder: "Select a country",
        tooltipMessage: "This license is a joke and a nod to the community, not intended to be professional.",
        infoTooltip: "Meaning of elements:\n- Generations: TruckersMP started in 2013 and VTCs in 2019. Generations are calculated by approximating the profile and VTC registration year.\n- Gold star (✵) next to name: Indicates the user is a VTC owner. It can be requested by opening a ticket in the LAG'S SPEED Discord.\n- Silver stars (★) on the right: A nod to the extinct VTC Convoy Nocturno.\n- Checkmark (✓) next to date: Indicates the date is from a reliable online source. Refresh the page to try fetching the date online again.\n- Cross (✗) next to date: Indicates the date is local, not verified. Refresh the page to try fetching the date online again.\n- A nocturnal verse whispers a secret, what word unlocks the hidden path?"
    },
    pt: {
        pageTitle: "Convoyrama | Gerador de Licença",
        headerTitle: "Gerador de Licença de Motorista",
        navLicense: "Licença",
        nameLabel: "Nome:",
        nicknameLabel: "TAG Épico:",
        titleToggleLabel: "Usar título cômico:",
        photoLabel: "Foto (Opcional):",
        countryLabel: "País:",
        companyLinkLabel: "Link do Perfil da Empresa no TruckersMP:",
        truckersmpLinkLabel: "Link do Perfil no TruckersMP:",
        customTitleLabel: "Alterar título:",
        watermarkToggleLabel: "Usar marca d'água:",
        qrColorToggleLabel: "Cor do QR: Escuro / Claro",
        vtcLogoLabel: "Logo VTC (Opcional):",
        backgroundToggleLabel: "Fundo:",
        colorLabel: "Tom do fundo:",
        saturationLabel: "Saturação:",
        customTitlePlaceholder: "Título personalizado (máx. 36 caracteres, opcional)",
        validLink: "Link válido",
        invalidLink: "Link inválido: deve ser https://truckersmp.com/user/[...]",
        validCompanyLink: "Link de empresa válido",
        invalidCompanyLink: "Link inválido: deve ser https://truckersmp.com/vtc/[...]",
        downloadButton: "Baixar Licença",
        canvasName: "Nome :",
        canvasLicenseNo: "Núm. Licença :",
        canvasLevel: "Geração :",
        canvasDate: "Data :",
        canvasCountry: "País :",
        canvasTag: "TAG :",
        levelFormat: "{0}{1}",
        titleNormal: "LICENÇA INTERNACIONAL DE CONDUÇÃO",
        titleComedic: "PERMISSÃO PARA CAUSAR CAOS EM COMBOIO",
        countryPlaceholder: "Selecione um país",
        tooltipMessage: "Esta licença é uma brincadeira e uma homenagem à comunidade, não pretende ser profissional.",
        infoTooltip: "Significado dos elementos:\n- Gerações: TruckersMP começou em 2013 e as VTCs em 2019. As gerações são calculadas aproximando o ano de registro do perfil e da VTC.\n- Estrela dourada (✵) ao lado do nome: Indica que o usuário é dono de uma VTC. Pode ser solicitada abrindo um ticket no Discord do LAG'S SPEED.\n- Estrelas prateadas (★) à direita: Uma homenagem à extinta VTC Convoy Nocturno.\n- Marca de verificação (✓) ao lado da data: Indica que a data vem de uma fonte online confiável. Atualize a página para tentar obter a data online novamente.\n- Cruz (✗) ao lado da data: Indica que a data é local, não verificada. Atualize a página para tentar obter a data online novamente.\n- Um verso noturno sussurra um segredo, que palavra desvenda o caminho oculto?"
    }
};
